---
- name: Install Batch Base Packages
  yum:
    name: '{{ bat_packages }}'
    state: present
    update_cache: yes
    disable_gpg_check: true

- name: Set owner and group for /platform
  ansible.builtin.file:
    path: '/platform/fi{{ fi_name }}'
    owner: 'us{{ fi_name }}'
    group: 'us{{ fi_name }}'
    recurse: yes