---
- name: create ihsadmin user
  ansible.builtin.user:
    name: 'ihsadmin'
    shell: /bin/ksh
    groups: uob
    append: yes
    state: present

- name: Install web packages
  yum:
    name: '{{ web_packages }}'
    state: present
    update_cache: yes

- name: create ihsgroup
  group:
    name: ihsgroup
    state: present

- name: add ihsadmin to ihsgroup
  user:
    name: ihsadmin
    groups: ihsgroup
    append: yes

- name: Set password for ihsadmin user
  user:
    name: mqm
    password: "{{ ihsadmin_pw | password_hash('sha512', 'mysecretsalt') }}"

- name: Add ihsadmin to cron.allow file
  lineinfile:
    path: /etc/cron.allow
    line: 'ihsadmin'

- name: change ownership of /platform directory to ihsadmin recursively
  file:
    path: /platform
    owner: ihsadmin
    group: ihsadmin
    recurse: yes
    state: directory

- name: Set ACLs for /platform
  ansible.builtin.acl:
    path: /platform
    entity: ihsadmin
    etype: user
    permissions: rwx
    state: present
    recursive: yes
    default: yes