# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # upon creation of a file that matches the pattern *sops.json,
  - filename_regex: \.sops\.json$
    kms: 'arn:aws:kms:us-east-1:207348267374:key/e8072b24-afa9-4346-a50e-910e4818041a'
