import { DfAccounts } from '@dragonfly/utils';
import { UpfConfig, UpfDbConfig } from './upfConfig';

/**
 * Class defining the upf db configurations
 */
export abstract class UpfEwbUatDbConfig extends UpfConfig {
  public static configuration: UpfDbConfig = {
    upf01: {
      id: 'ewb-upf-01',
      route53Name: 'dbu1ewu3.uat',
      engine: 'oracle-ee',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBU1EWU3',
      sopsDbProperty: 'dbupewi3upf',
      prodCustomerData: true,
      optionGroupName: 'ewb-upf-01-option-group-est'.toLowerCase(),
      timezone: 'America/New_York',
      additionalSgCidrBlocks: [
        DfAccounts.getSharedUatAccountDef().vpcCidrs.main.primary,
      ],
    },
    upf02: {
      id: 'ewb-upf-02',
      route53Name: 'dbu2ewu3.uat',
      engine: 'oracle-ee',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBU2EWU3',
      sopsDbProperty: 'dbupewi3upf',
      prodCustomerData: true,
      optionGroupName: 'ewb-upf-02-option-group-est'.toLowerCase(),
      timezone: 'America/New_York',
      additionalSgCidrBlocks: [
        DfAccounts.getSharedUatAccountDef().vpcCidrs.main.primary,
      ],
    },
    upf03: {
      id: 'ewb02-upf-01',
      route53Name: 'dbu1ewu2.uat',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 50,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBU1EWU2',
      sopsDbProperty: 'dbupewi2upf',
      prodCustomerData: true,
      optionGroupName: 'ewb02-upf-01-option-group-est-se2'.toLowerCase(),
      timezone: 'America/New_York',
      additionalSgCidrBlocks: [
        DfAccounts.getSharedUatAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
    },
    upf04: {
      id: 'ewb02-upf-02',
      route53Name: 'dbu2ewu2.uat',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 50,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBU2EWU2',
      sopsDbProperty: 'dbupewi2upf',
      prodCustomerData: true,
      optionGroupName: 'ewb02-upf-02-option-group-est-se2'.toLowerCase(),
      timezone: 'America/New_York',
      additionalSgCidrBlocks: [
        DfAccounts.getSharedUatAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
    },
    upf05: {
      id: 'ewbk-upf-01',
      route53Name: 'dbu1ewu1.uat',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 50,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBU1EWU1',
      sopsDbProperty: 'dbewbkupf',
      prodCustomerData: true,
      optionGroupName: 'ewbk-upf-01-option-group-est-se2'.toLowerCase(),
      timezone: 'America/New_York',
      additionalSgCidrBlocks: [
        DfAccounts.getSharedUatAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
    },
    upf06: {
      id: 'ewbk-upf-02',
      route53Name: 'dbu2ewu1.uat',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 50,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBU2EWU1',
      sopsDbProperty: 'dbewbkupf',
      prodCustomerData: true,
      optionGroupName: 'ewbk-upf-02-option-group-est-se2'.toLowerCase(),
      timezone: 'America/New_York',
      additionalSgCidrBlocks: [
        DfAccounts.getSharedUatAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
    },
  };
}
