import { UpfConfig, UpfDbConfig } from './upfConfig';

/**
 * Class defining the upf db configurations
 */
export abstract class UpfIstDbConfig extends UpfConfig {
  public static configuration: UpfDbConfig = {
    upf01: {
      id: 'ist-sant-ist1-upf-OracleInstance'.toLowerCase(),
      route53Name: 'dbsantupf01.ist',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBUPSNI1',
      sopsDbProperty: 'santist1upf',
      parameterGroupConfig: {
        name: 'sant-ist1-upf-OracleInstance-upf-params'.toLowerCase(),
        family: 'oracle-se2-19',
      },
      optionGroupName: 'ist-sant-ist1-upf-est-se2'.toLowerCase(),
      timezone: 'America/New_York',
    },
    upf02: {
      id: 'muob-upf-01'.toLowerCase(),
      route53Name: 'dbupmui1.ist',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBUPMUI1',
      sopsDbProperty: 'dbupmui1',
      parameterGroupConfig: {
        name: 'muob-upf-01-upf-params'.toLowerCase(),
        family: 'oracle-se2-19',
      },
      optionGroupName: 'muob-upf-01-option-group-est-se2'.toLowerCase(),
      timezone: 'America/New_York',
    },
    upf03: {
      id: 'ewbki1-upf-01'.toLowerCase(),
      route53Name: 'dbupewi1.ist',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBUPEWI1',
      sopsDbProperty: 'dbewbki1upf',
      parameterGroupConfig: {
        name: 'ewbki1-upf-01-upf-params'.toLowerCase(),
        family: 'oracle-se2-19',
      },
      optionGroupName: 'ewbki1-upf-01-option-group-est-se2'.toLowerCase(),
      timezone: 'America/New_York',
    },
    upf05: {
      id: 'dbu1mod-upf'.toLowerCase(),
      route53Name: 'dbu1mod.ist',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 50,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBU1MOD',
      sopsDbProperty: 'istmodupf',
      parameterGroupConfig: {
        name: 'oracle-mod1-se2'.toLowerCase(),
        family: 'oracle-se2-19',
      },
      timezone: 'America/New_York',
    },
    upf06: {
      id: 'dbu2mod-upf'.toLowerCase(),
      route53Name: 'dbu2mod.ist',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 50,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'DBU2MOD',
      sopsDbProperty: 'istmodupf',
      parameterGroupConfig: {
        name: 'oracle-mod2-se2'.toLowerCase(),
        family: 'oracle-se2-19',
      },
      timezone: 'America/New_York',
    },
    upf07: {
      id: 'csi-upf-01'.toLowerCase(),
      route53Name: 'dbupcsi1.ist',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 50,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      parameterGroupConfig: {
        name: 'csi-upf-oracle-se2-19',
        family: 'oracle-se2-19',
        parameter: [
          {
            name: 'open_cursors',
            value: '2000',
          },
        ],
      },
      createBucket: false,
      dbName: 'DBUPCSI1',
      timezone: 'America/New_York',
      sopsDbProperty: 'istcsiupf',
    },
    upf08: {
      id: 'muobi2-upf-01'.toLowerCase(),
      route53Name: 'dbupmui2.ist',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 50,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      parameterGroupConfig: {
        name: 'muobi2-upf-oracle-se2-19',
        family: 'oracle-se2-19',
        parameter: [
          {
            name: 'open_cursors',
            value: '2000',
          },
        ],
      },
      createBucket: false,
      dbName: 'DBUPMUI2',
      timezone: 'America/New_York',
      sopsDbProperty: 'istmuobi2upf',
    },
  };
}
