import { DfAccounts } from '@dragonfly/utils';
import { UpfConfig, UpfDbConfig } from './upfConfig';

/**
 * Class defining the upf db configurations
 */
export abstract class UpfMuobProdDbConfig extends UpfConfig {
  public static configuration: UpfDbConfig = {
    muobUpf01: {
      id: 'muob-upf-01',
      route53Name: 'dbu1muob1.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP1MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      optionGroupName: 'muobprod01-upf-se',
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: `muobprod01-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf02: {
      id: 'muob-upf-02',
      route53Name: 'dbu1muob2.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP2MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod02-upf-se',
      parameterGroupConfig: {
        name: `muobprod02-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf03: {
      id: 'muob-upf-03',
      route53Name: 'dbu1muob3.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP3MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod03-upf-se',
      parameterGroupConfig: {
        name: `muobprod03-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf04: {
      id: 'muob-upf-04',
      route53Name: 'dbu1muob4.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP4MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod04-upf-se',
      parameterGroupConfig: {
        name: `muobprod04-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf05: {
      id: 'muob-upf-05',
      route53Name: 'dbu1muob5.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP5MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod05-upf-se',
      parameterGroupConfig: {
        name: `muobprod05-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf06: {
      id: 'muob-upf-06',
      route53Name: 'dbu1muob6.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP6MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod06-upf-se',
      parameterGroupConfig: {
        name: `muobprod06-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf07: {
      id: 'muob-upf-07',
      route53Name: 'dbu1muob7.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP7MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod07-upf-se',
      parameterGroupConfig: {
        name: `muobprod07-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf08: {
      id: 'muob-upf-08',
      route53Name: 'dbu1muob8.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP8MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod08-upf-se',
      parameterGroupConfig: {
        name: `muobprod08-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf09: {
      id: 'muob-upf-09',
      route53Name: 'dbu1muob9.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP9MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod09-upf-se',
      parameterGroupConfig: {
        name: `muobprod09-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf10: {
      id: 'muob-upf-10',
      route53Name: 'dbu1muob10.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1U10MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod10-upf-se',
      parameterGroupConfig: {
        name: `muobprod10-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf11: {
      id: 'muob-upf-11',
      route53Name: 'dbu1muob11.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1U11MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod11-upf-se',
      parameterGroupConfig: {
        name: `muobprod11-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf12: {
      id: 'muob-upf-12',
      route53Name: 'dbu2muob1.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP1MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod12-upf-se',
      parameterGroupConfig: {
        name: `muobprod12-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf13: {
      id: 'muob-upf-13',
      route53Name: 'dbu2muob2.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP2MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod13-upf-se',
      parameterGroupConfig: {
        name: `muobprod13-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf14: {
      id: 'muob-upf-14',
      route53Name: 'dbu2muob3.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP3MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod14-upf-se',
      parameterGroupConfig: {
        name: `muobprod14-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf15: {
      id: 'muob-upf-15',
      route53Name: 'dbu2muob4.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP4MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod15-upf-se',
      parameterGroupConfig: {
        name: `muobprod15-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf16: {
      id: 'muob-upf-16',
      route53Name: 'dbu2muob5.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP5MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod16-upf-se',
      parameterGroupConfig: {
        name: `muobprod16-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf17: {
      id: 'muob-upf-17',
      route53Name: 'dbu2muob6.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP6MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod17-upf-se',
      parameterGroupConfig: {
        name: `muobprod17-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf18: {
      id: 'muob-upf-18',
      route53Name: 'dbu2muob7.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP7MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod18-upf-se',
      parameterGroupConfig: {
        name: `muobprod18-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf19: {
      id: 'muob-upf-19',
      route53Name: 'dbu2muob8.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP8MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod19-upf-se',
      parameterGroupConfig: {
        name: `muobprod19-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf20: {
      id: 'muob-upf-20',
      route53Name: 'dbu2muob9.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP9MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod20-upf-se',
      parameterGroupConfig: {
        name: `muobprod20-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf21: {
      id: 'muob-upf-21',
      route53Name: 'dbu2muob10.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2U10MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod21-upf-se',
      parameterGroupConfig: {
        name: `muobprod21-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobUpf22: {
      id: 'muob-upf-22',
      route53Name: 'dbu2muob11.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2U11MP1',
      sopsDbProperty: 'dbmuobprodupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      optionGroupName: 'muobprod22-upf-se',
      parameterGroupConfig: {
        name: `muobprod22-upf-params`.toLowerCase(),
        family: 'oracle-se2-19',
      },
      multiRegionKey: true,
    },
    muobp2Upf01: {
      id: 'muobp2-upf-01',
      route53Name: 'dbu1muob1p2.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP1MP2',
      sopsDbProperty: 'dbmuobp2produpf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: `muobp2-upf-01`,
        family: 'oracle-se2-19',
      },
    },
    muobp2Upf02: {
      id: 'muobp2-upf-02',
      route53Name: 'dbu2muob1p2.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP1MP2',
      sopsDbProperty: 'dbmuobp2produpf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.primary,
      ],
      availabilityZone: 'us-east-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: `muobp2-upf-02`,
        family: 'oracle-se2-19',
      },
    },
  };
}
