import { DfAccounts } from '@dragonfly/utils';
import { UpfConfig, UpfDbConfig } from './upfConfig';

/**
 * Class defining the upf db configurations
 */
export abstract class UpfMuobProdDrDbConfig extends UpfConfig {
  public static configuration: UpfDbConfig = {
    dbu1MuobUpfDr01: {
      id: 'dbu1-muob-upf-dr-01',
      route53Name: 'dbu1muob1-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP1MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-01',
        family: 'oracle-se2-19',
      },
    },
    dbu1MuobUpfDr02: {
      id: 'dbu1-muob-upf-dr-02',
      route53Name: 'dbu1muob2-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP2MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-02',
        family: 'oracle-se2-19',
      },
    },
    dbu1MuobUpfDr03: {
      id: 'dbu1-muob-upf-dr-03',
      route53Name: 'dbu1muob3-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP3MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-03',
        family: 'oracle-se2-19',
      },
    },
    dbu1MuobUpfDr04: {
      id: 'dbu1-muob-upf-dr-04',
      route53Name: 'dbu1muob4-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP4MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-04',
        family: 'oracle-se2-19',
      },
    },
    dbu1MuobUpfDr05: {
      id: 'dbu1-muob-upf-dr-05',
      route53Name: 'dbu1muob5-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP5MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-05',
        family: 'oracle-se2-19',
      },
    },
    dbu1MuobUpfDr06: {
      id: 'dbu1-muob-upf-dr-06',
      route53Name: 'dbu1muob6-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP6MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-06',
        family: 'oracle-se2-19',
      },
    },
    dbu1MuobUpfDr07: {
      id: 'dbu1-muob-upf-dr-07',
      route53Name: 'dbu1muob7-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP7MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-07',
        family: 'oracle-se2-19',
      },
    },
    dbu1MuobUpfDr08: {
      id: 'dbu1-muob-upf-dr-08',
      route53Name: 'dbu1muob8-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP8MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-08',
        family: 'oracle-se2-19',
      },
    },
    dbu1MuobUpfDr09: {
      id: 'dbu1-muob-upf-dr-09',
      route53Name: 'dbu1muob9-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP9MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-09',
        family: 'oracle-se2-19',
      },
    },
    dbu1MuobUpfDr10: {
      id: 'dbu1-muob-upf-dr-10',
      route53Name: 'dbu1muob10-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1U10MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu1-muob-upf-dr-10',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr01: {
      id: 'dbu2-muob-upf-dr-01',
      route53Name: 'dbu2muob1-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP1MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-01',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr02: {
      id: 'dbu2-muob-upf-dr-02',
      route53Name: 'dbu2muob2-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP2MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-02',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr03: {
      id: 'dbu2-muob-upf-dr-03',
      route53Name: 'dbu2muob3-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP3MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-03',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr04: {
      id: 'dbu2-muob-upf-dr-04',
      route53Name: 'dbu2muob4-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP4MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-04',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr05: {
      id: 'dbu2-muob-upf-dr-05',
      route53Name: 'dbu2muob5-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP5MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-05',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr06: {
      id: 'dbu2-muob-upf-dr-06',
      route53Name: 'dbu2muob6-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP6MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-06',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr07: {
      id: 'dbu2-muob-upf-dr-07',
      route53Name: 'dbu2muob7-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP7MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-07',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr08: {
      id: 'dbu2-muob-upf-dr-08',
      route53Name: 'dbu2muob8-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP8MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-08',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr09: {
      id: 'dbu2-muob-upf-dr-09',
      route53Name: 'dbu2muob9-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP9MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-09',
        family: 'oracle-se2-19',
      },
    },
    dbu2MuobUpfDr10: {
      id: 'dbu2-muob-upf-dr-10',
      route53Name: 'dbu2muob10-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2U10MP1',
      sopsDbProperty: 'dbmuobproddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: 'dbu2-muob-upf-dr-10',
        family: 'oracle-se2-19',
      },
    },
    muobp2Upf01: {
      id: 'muobp2-upf-dr-01',
      route53Name: 'dbu1muob1p2-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D1UP1MP2',
      sopsDbProperty: 'dbmuobp2proddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2a',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: `muobp2-upf-dr-01`,
        family: 'oracle-se2-19',
      },
    },
    muobp2Upf02: {
      id: 'muobp2-upf-dr-02',
      route53Name: 'dbu2muob1p2-dr.prod',
      engine: 'oracle-se2',
      engineVersion: '19',
      storageType: 'gp3',
      allocatedStorage: 250,
      instanceClass: 'db.t3.medium',
      performanceInsightsEnabled: true,
      createBucket: false,
      dbName: 'D2UP1MP2',
      sopsDbProperty: 'dbmuobp2proddrupf',
      prodCustomerData: true,
      additionalSgCidrBlocks: [
        DfAccounts.getSharedProdAccountDef().vpcCidrs.main.recovery,
      ],
      availabilityZone: 'us-west-2b',
      timezone: 'America/New_York',
      parameterGroupConfig: {
        name: `muobp2-upf-dr-02`,
        family: 'oracle-se2-19',
      },
    },
  };
}
