name: audit
on: workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: audit
        run: npm audit --omit=dev --audit-level=high
