name: synth
on: workflow_call
jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: nx and cdktf-cli install
        run: npm install nx cdktf-cli -g

      - name: npm install
        run: npm install --include=optional

      - name: synth
        run: ./buildAssets/scripts/synth-all-build-configs.sh
